### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by MMMUFFINS** [MMMUFFINS/discord-wows-stats-bot#11]
```
 !stats blackwolf56 na
[10:04 PM] BOTStatsbot: @user, Cannot read property 'data' of undefined
```

**Comment by MMMUFFINS** [comment]
```
300ConfirmedKills: !stats flamu eu
[10:38 AM] BOTStatsbot: @300ConfirmedKills, Cannot read property 'data' of undefined
```

**Comment by MMMUFFINS** [comment]
```
user: !stats flamu eu
[10:38 AM] BOTStatsbot: @user, Cannot read property 'data' of undefined
```

**Comment by MMMUFFINS** [comment]
This seems to be the bot not having received the expected values from WN (or somehow got corrupted).

```
{ nickname: 'WaterBoi', account_id: 1003476975, clan: null }
statsbot_1  | TypeError: Cannot read property 'data' of undefined
statsbot_1  |     at Lookup.calculatePr (/usr/src/app/includes/lookup.js:151:59)
statsbot_1  |     at wg.getPvpShipsData.then (/usr/src/app/includes/main.js:114:37)
statsbot_1  |     at <anonymous>
statsbot_1  |     at process._tickCallback (internal/process/next_tick.js:188:7)
```

Expose the updater as a Promise function (first in lookup, then in main.js) and call the rest of the index.js after it resolves.
