### ISSUE TITLE
Bot dies when receiving a non-command message

### ISSUE THREAD

**Issue by MMMUFFINS** [MMMUFFINS/discord-wows-stats-bot#16]
```
statsbot_1  | /usr/src/app/index.js:44
statsbot_1  |         .then((reply) => {
statsbot_1  |         ^
statsbot_1  |
statsbot_1  | TypeError: Cannot read property 'then' of undefined
statsbot_1  |     at Client.client.on.message (/usr/src/app/index.js:44:9)
statsbot_1  |     at emitOne (events.js:116:13)
statsbot_1  |     at Client.emit (events.js:211:7)
statsbot_1  |     at MessageCreateHandler.handle (/usr/src/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
statsbot_1  |     at WebSocketPacketManager.handle (/usr/src/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
statsbot_1  |     at WebSocketConnection.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
statsbot_1  |     at WebSocketConnection.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
statsbot_1  |     at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/EventTarget.js:99:16)
statsbot_1  |     at emitOne (events.js:116:13)
statsbot_1  |     at WebSocket.emit (events.js:211:7)
statsbot_1  | npm ERR! code ELIFECYCLE
statsbot_1  | npm ERR! errno 1
statsbot_1  | npm ERR! discord-wows-stats-bot@1.0.0 start: `node index.js`
statsbot_1  | npm ERR! Exit status 1
statsbot_1  | npm ERR!
statsbot_1  | npm ERR! Failed at the discord-wows-stats-bot@1.0.0 start script.
statsbot_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
statsbot_1  |
statsbot_1  | npm ERR! A complete log of this run can be found in:
statsbot_1  | npm ERR!     /root/.npm/_logs/2018-01-02T01_58_09_707Z-debug.log
```

**Comment by MMMUFFINS** [comment]
The issue is that when a message is received but the bot is not called, the handler returns nothing. But index.js is looking for a promise to call .then() on, and since it doesn't receive one it borks.
